[package]
name = "meson-next"
version = "1.2.0"
authors = ["dovee <dovee@users.noreply.github.com>","Brandon Piña"]
description = "Forked from meson by dovee"
documentation = "https://docs.rs/meson/1.0.0"
license = "MIT"

[dependencies]
